/**
 * HidroGrow — catálogo de genéticas (alias CULTIVOS_DB en cultivos-db.js).
 * Campos compatibles con el motor: id, nombre, abrev, grupo, emoji, ec/ph, dias, sistemaIdeal, nota, fructificacion.
 * Extra: tipoFloracion (foto|auto), diasVeg, diasFlor.
 */
const GENETICS_DB = [
  { id: 'northern_lights_auto', nombre: 'Northern Lights Auto', abrev: 'NL', grupo: 'auto', emoji: '🌿',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 49, dias: 70,
    ecMin: 1200, ecMax: 1800, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc,torre',
    nota: 'Indica autofloreciente clásica. Compacta, ideal DWC o RDWC.', fructificacion: true },
  { id: 'blue_dream', nombre: 'Blue Dream', abrev: 'BD', grupo: 'hibrida', emoji: '🫐',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc,nft',
    nota: 'Híbrido sativa-dominante. Necesita espacio vertical en floración.', fructificacion: true },
  { id: 'og_kush', nombre: 'OG Kush', abrev: 'OG', grupo: 'indica', emoji: '🌲',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2000, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica potente. Controlar humedad en floración tardía.', fructificacion: true },
  { id: 'white_widow', nombre: 'White Widow', abrev: 'WW', grupo: 'hibrida', emoji: '❄️',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc,torre',
    nota: 'Equilibrada, resina abundante. Buena para primeros cultivos en hidro.', fructificacion: true },
  { id: 'amnesia_haze', nombre: 'Amnesia Haze', abrev: 'AH', grupo: 'sativa', emoji: '☀️',
    tipoFloracion: 'foto', diasVeg: 49, diasFlor: 70, dias: 119,
    ecMin: 1400, ecMax: 2300, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc,nft',
    nota: 'Sativa alta. Fotoperiodo 12/12 con paciencia en floración.', fructificacion: true },
  { id: 'girl_scout_cookies', nombre: 'Girl Scout Cookies', abrev: 'GSC', grupo: 'hibrida', emoji: '🍪',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Engorde exigente en EC. Vigilar pH estable en recirculación.', fructificacion: true },
  { id: 'gorilla_glue', nombre: 'Gorilla Glue #4', abrev: 'GG4', grupo: 'hibrida', emoji: '🦍',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1500, ecMax: 2400, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Muy resinosa. RDWC con buena aireación en raíces.', fructificacion: true },
  { id: 'ak47', nombre: 'AK-47', abrev: 'AK', grupo: 'hibrida', emoji: '⚡',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2000, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc,torre,nft',
    nota: 'Versátil y productiva. Tolera bien variaciones moderadas de EC.', fructificacion: true },
  { id: 'critical_mass', nombre: 'Critical Mass', abrev: 'CM', grupo: 'indica', emoji: '🏋️',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1300, ecMax: 2000, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Cogollos pesados. Refuerza soporte de ramas en floración.', fructificacion: true },
  { id: 'cheese', nombre: 'Cheese', abrev: 'CH', grupo: 'indica', emoji: '🧀',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Aroma intenso. Filtro de carbón recomendado en sala.', fructificacion: true },
  { id: 'sour_diesel', nombre: 'Sour Diesel', abrev: 'SD', grupo: 'sativa', emoji: '⛽',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 70, dias: 112,
    ecMin: 1400, ecMax: 2300, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc,nft',
    nota: 'Sativa energética. Estira en preflor; planifica altura de lámpara.', fructificacion: true },
  { id: 'jack_herer', nombre: 'Jack Herer', abrev: 'JH', grupo: 'sativa', emoji: '🌞',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc,nft',
    nota: 'Clásica sativa. Buena respuesta a EC media-alta en floración.', fructificacion: true },
  { id: 'purple_haze', nombre: 'Purple Haze', abrev: 'PH', grupo: 'sativa', emoji: '💜',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa legendaria. Temperaturas nocturnas bajas realzan color.', fructificacion: true },
  { id: 'durban_poison', nombre: 'Durban Poison', abrev: 'DP', grupo: 'sativa', emoji: '🇿🇦',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1300, ecMax: 2100, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc,nft',
    nota: 'Sativa pura. Ciclo largo; excelente en climas cálidos.', fructificacion: true },
  { id: 'bruce_banner', nombre: 'Bruce Banner', abrev: 'BB', grupo: 'hibrida', emoji: '💪',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1500, ecMax: 2400, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Alta potencia. Subir EC de forma gradual en floración.', fructificacion: true },
  { id: 'wedding_cake', nombre: 'Wedding Cake', abrev: 'WC', grupo: 'hibrida', emoji: '🎂',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica-dominante. Vigilar humedad relativa <50% en floración densa.', fructificacion: true },
  { id: 'zkittlez_auto', nombre: 'Zkittlez Auto', abrev: 'ZK', grupo: 'auto', emoji: '🍬',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 56, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc,torre',
    nota: 'Autofloreciente aromática. No trasplantar tarde; raíz estable desde inicio.', fructificacion: true },
  { id: 'green_crack', nombre: 'Green Crack', abrev: 'GC', grupo: 'sativa', emoji: '🌿',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc,nft',
    nota: 'Sativa vigorosa. Podas de altura en vegetativo recomendadas.', fructificacion: true },
  { id: 'strawberry_cough', nombre: 'Strawberry Cough', abrev: 'SC', grupo: 'sativa', emoji: '🍓',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc,nft',
    nota: 'Sativa con estiramiento marcado en 12/12.', fructificacion: true },
  { id: 'gelato', nombre: 'Gelato', abrev: 'GL', grupo: 'hibrida', emoji: '🍨',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Cogollos densos. Buena aireación bajo copa en sala.', fructificacion: true },
  { id: 'mimosa', nombre: 'Mimosa', abrev: 'MI', grupo: 'hibrida', emoji: '🥂',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa-dominante moderna. Terpenos intensos; temperatura estable.', fructificacion: true },
  { id: 'purple_kush', nombre: 'Purple Kush', abrev: 'PK', grupo: 'indica', emoji: '🔮',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica compacta. Ideal salas pequeñas y RDWC.', fructificacion: true },
  { id: 'la_confidential', nombre: 'LA Confidential', abrev: 'LA', grupo: 'indica', emoji: '🌃',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica de perfil bajo. Poca altura, buena para armarios.', fructificacion: true },
  { id: 'pineapple_express', nombre: 'Pineapple Express', abrev: 'PE', grupo: 'hibrida', emoji: '🍍',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc,nft',
    nota: 'Híbrida equilibrada. Crecimiento vigoroso pero manejable.', fructificacion: true },
  { id: 'afghan_kush', nombre: 'Afghan Kush', abrev: 'AF', grupo: 'indica', emoji: '🏔️',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1800, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica landrace. Resistente; EC moderada suficiente.', fructificacion: true },
  { id: 'charlottes_web', nombre: "Charlotte's Web", abrev: 'CW', grupo: 'cbd', emoji: '🩺',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1000, ecMax: 1600, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc,nft',
    nota: 'Perfil CBD. EC más baja que genéticas THC altas.', fructificacion: true },
  { id: 'harlequin', nombre: 'Harlequin', abrev: 'HQ', grupo: 'cbd', emoji: '💚',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1000, ecMax: 1600, phMin: 5.9, phMax: 6.3, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'CBD dominante. Relación THC:CBD equilibrada.', fructificacion: true },
  { id: 'moby_dick_auto', nombre: 'Moby Dick Auto', abrev: 'MD', grupo: 'auto', emoji: '🐋',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 63, dias: 84,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Auto sativa-dominante. Altura media; buena luz en floración.', fructificacion: true },
  { id: 'forbidden_fruit', nombre: 'Forbidden Fruit', abrev: 'FF', grupo: 'hibrida', emoji: '🍇',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Aroma frutal intenso. Coloración en frío nocturno.', fructificacion: true },
  { id: 'skunk1', nombre: 'Skunk #1', abrev: 'SK', grupo: 'hibrida', emoji: '🦨',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2000, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc,torre',
    nota: 'Genética histórica. Referencia para cultivos en hidro.', fructificacion: true },
];
