/**
 * HidroGrow — catálogo de genéticas (100+ variedades; alias CULTIVOS_DB en cultivos-db.js).
 * Campos compatibles con el motor: id, nombre, abrev, grupo, emoji, ec/ph, dias, sistemaIdeal, nota, fructificacion.
 * Extra: tipoFloracion (foto|auto), diasVeg, diasFlor, breederId, strainPackUrl (vía hc-genetics-breeder.js).
 * Incluye variedades de las marcas top España: Spain Seeds, Ripper Seeds, BSF Seeds, Buddha Seeds, Advanced Seeds,
 * 00 Seeds, ACE Seeds, Genehtik Seeds, Reggae Seeds, Anesia Seeds, GB Strains, Perfect Tree Seeds, Sweet Seeds,
 * Silent Seeds, Barney's Farm, Green House Seeds, DNA Genetics, Humboldt Seed Company, Fast Buds.
 */
const GENETICS_DB = [
  { id: 'northern_lights_auto', nombre: 'Northern Lights Auto', abrev: 'NL', grupo: 'auto', emoji: '🌿',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 49, dias: 70,
    ecMin: 1200, ecMax: 1800, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica autofloreciente clásica. Compacta, ideal DWC o RDWC.', fructificacion: true },
  { id: 'blue_dream', nombre: 'Blue Dream', abrev: 'BD', grupo: 'hibrida', emoji: '🫐',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Híbrido sativa-dominante. Necesita espacio vertical en floración.', fructificacion: true },
  { id: 'og_kush', nombre: 'OG Kush', abrev: 'OG', grupo: 'indica', emoji: '🌲',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2000, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica potente. Controlar humedad en floración tardía.', fructificacion: true },
  { id: 'white_widow', nombre: 'White Widow', abrev: 'WW', grupo: 'hibrida', emoji: '❄️',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Equilibrada, resina abundante. Buena para primeros cultivos en hidro.', fructificacion: true },
  { id: 'amnesia_haze', nombre: 'Amnesia Haze', abrev: 'AH', grupo: 'sativa', emoji: '☀️',
    tipoFloracion: 'foto', diasVeg: 49, diasFlor: 70, dias: 119,
    ecMin: 1400, ecMax: 2300, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa alta. Fotoperiodo 12/12 con paciencia en floración.', fructificacion: true },
  { id: 'girl_scout_cookies', nombre: 'Girl Scout Cookies', abrev: 'GSC', grupo: 'hibrida', emoji: '🍪',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Engorde exigente en EC. Vigilar pH estable en recirculación.', fructificacion: true },
  { id: 'gorilla_glue', nombre: 'Gorilla Glue #4', abrev: 'GG4', grupo: 'hibrida', emoji: '🦍',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1500, ecMax: 2400, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Muy resinosa. RDWC con buena aireación en raíces.', fructificacion: true },
  { id: 'ak47', nombre: 'AK-47', abrev: 'AK', grupo: 'hibrida', emoji: '⚡',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2000, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Versátil y productiva. Tolera bien variaciones moderadas de EC.', fructificacion: true },
  { id: 'critical_mass', nombre: 'Critical Mass', abrev: 'CM', grupo: 'indica', emoji: '🏋️',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1300, ecMax: 2000, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Cogollos pesados. Refuerza soporte de ramas en floración.', fructificacion: true },
  { id: 'cheese', nombre: 'Cheese', abrev: 'CH', grupo: 'indica', emoji: '🧀',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Aroma intenso. Filtro de carbón recomendado en sala.', fructificacion: true },
  { id: 'sour_diesel', nombre: 'Sour Diesel', abrev: 'SD', grupo: 'sativa', emoji: '⛽',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 70, dias: 112,
    ecMin: 1400, ecMax: 2300, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa energética. Estira en preflor; planifica altura de lámpara.', fructificacion: true },
  { id: 'jack_herer', nombre: 'Jack Herer', abrev: 'JH', grupo: 'sativa', emoji: '🌞',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Clásica sativa. Buena respuesta a EC media-alta en floración.', fructificacion: true },
  { id: 'purple_haze', nombre: 'Purple Haze', abrev: 'PH', grupo: 'sativa', emoji: '💜',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa legendaria. Temperaturas nocturnas bajas realzan color.', fructificacion: true },
  { id: 'durban_poison', nombre: 'Durban Poison', abrev: 'DP', grupo: 'sativa', emoji: '🇿🇦',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1300, ecMax: 2100, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa pura. Ciclo largo; excelente en climas cálidos.', fructificacion: true },
  { id: 'bruce_banner', nombre: 'Bruce Banner', abrev: 'BB', grupo: 'hibrida', emoji: '💪',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1500, ecMax: 2400, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Alta potencia. Subir EC de forma gradual en floración.', fructificacion: true },
  { id: 'wedding_cake', nombre: 'Wedding Cake', abrev: 'WC', grupo: 'hibrida', emoji: '🎂',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica-dominante. Vigilar humedad relativa <50% en floración densa.', fructificacion: true },
  { id: 'zkittlez_auto', nombre: 'Zkittlez Auto', abrev: 'ZK', grupo: 'auto', emoji: '🍬',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 56, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Autofloreciente aromática. No trasplantar tarde; raíz estable desde inicio.', fructificacion: true },
  { id: 'green_crack', nombre: 'Green Crack', abrev: 'GC', grupo: 'sativa', emoji: '🌿',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa vigorosa. Podas de altura en vegetativo recomendadas.', fructificacion: true },
  { id: 'strawberry_cough', nombre: 'Strawberry Cough', abrev: 'SC', grupo: 'sativa', emoji: '🍓',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa con estiramiento marcado en 12/12.', fructificacion: true },
  { id: 'gelato', nombre: 'Gelato', abrev: 'GL', grupo: 'hibrida', emoji: '🍨',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Cogollos densos. Buena aireación bajo copa en sala.', fructificacion: true },
  { id: 'mimosa', nombre: 'Mimosa', abrev: 'MI', grupo: 'hibrida', emoji: '🥂',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa-dominante moderna. Terpenos intensos; temperatura estable.', fructificacion: true },
  { id: 'purple_kush', nombre: 'Purple Kush', abrev: 'PK', grupo: 'indica', emoji: '🔮',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica compacta. Ideal salas pequeñas y RDWC.', fructificacion: true },
  { id: 'la_confidential', nombre: 'LA Confidential', abrev: 'LA', grupo: 'indica', emoji: '🌃',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica de perfil bajo. Poca altura, buena para armarios.', fructificacion: true },
  { id: 'pineapple_express', nombre: 'Pineapple Express', abrev: 'PE', grupo: 'hibrida', emoji: '🍍',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Híbrida equilibrada. Crecimiento vigoroso pero manejable.', fructificacion: true },
  { id: 'afghan_kush', nombre: 'Afghan Kush', abrev: 'AF', grupo: 'indica', emoji: '🏔️',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1800, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica landrace. Resistente; EC moderada suficiente.', fructificacion: true },
  { id: 'charlottes_web', nombre: "Charlotte's Web", abrev: 'CW', grupo: 'cbd', emoji: '🩺',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1000, ecMax: 1600, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Perfil CBD. EC más baja que genéticas THC altas.', fructificacion: true },
  { id: 'harlequin', nombre: 'Harlequin', abrev: 'HQ', grupo: 'cbd', emoji: '💚',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1000, ecMax: 1600, phMin: 5.9, phMax: 6.3, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'CBD dominante. Relación THC:CBD equilibrada.', fructificacion: true },
  { id: 'moby_dick_auto', nombre: 'Moby Dick Auto', abrev: 'MD', grupo: 'auto', emoji: '🐋',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 63, dias: 84,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Auto sativa-dominante. Altura media; buena luz en floración.', fructificacion: true },
  { id: 'forbidden_fruit', nombre: 'Forbidden Fruit', abrev: 'FF', grupo: 'hibrida', emoji: '🍇',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Aroma frutal intenso. Coloración en frío nocturno.', fructificacion: true },
  { id: 'skunk1', nombre: 'Skunk #1', abrev: 'SK', grupo: 'hibrida', emoji: '🦨',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2000, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Genética histórica. Referencia para cultivos en hidro.', fructificacion: true },
  { id: 'royal_moby', nombre: 'Royal Moby', abrev: 'RM', grupo: 'sativa', emoji: '🐋',
    tipoFloracion: 'foto', diasVeg: 49, diasFlor: 70, dias: 119,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa gigante (Royal Queen). Altura y luz altas en floración.', fructificacion: true },
  { id: 'purple_queen', nombre: 'Purple Queen', abrev: 'PQ', grupo: 'indica', emoji: '👑',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 56, dias: 84,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica morada. Color en noches frescas; perfil compacto.', fructificacion: true },
  { id: 'skunk_xl', nombre: 'Skunk XL', abrev: 'SX', grupo: 'hibrida', emoji: '🦨',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Versión XL del Skunk. Producción alta en hidro recirculado.', fructificacion: true },
  { id: 'super_skunk', nombre: 'Super Skunk', abrev: 'SS', grupo: 'indica', emoji: '🦨',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 2000, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica clásica olor intenso. Filtro de carbón en floración.', fructificacion: true },
  { id: 'big_bud', nombre: 'Big Bud', abrev: 'BBu', grupo: 'indica', emoji: '🌸',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1300, ecMax: 2000, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Cogollos muy pesados. Redes y soporte de ramas obligatorios.', fructificacion: true },
  { id: 'lemon_haze', nombre: 'Lemon Haze', abrev: 'LH', grupo: 'sativa', emoji: '🍋',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 70, dias: 112,
    ecMin: 1400, ecMax: 2300, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa cítrica. Ciclo largo; EC media-alta en floración.', fructificacion: true },
  { id: 'trainwreck', nombre: 'Trainwreck', abrev: 'TW', grupo: 'hibrida', emoji: '🚂',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2200, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Híbrida vigorosa. Controlar estiramiento en cambio a 12/12.', fructificacion: true },
  { id: 'granddaddy_purple', nombre: 'Granddaddy Purple', abrev: 'GDP', grupo: 'indica', emoji: '🍇',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 56, dias: 84,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica morada legendaria. Baja altura; ideal armarios.', fructificacion: true },
  { id: 'bubba_kush', nombre: 'Bubba Kush', abrev: 'BK', grupo: 'indica', emoji: '🛋️',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica sedante. Cogollos densos; vigilar humedad en flor.', fructificacion: true },
  { id: 'dosidos', nombre: 'Do-Si-Dos', abrev: 'DS', grupo: 'hibrida', emoji: '🍪',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'GSC × Face Off. Resina abundante; pH estable en RDWC.', fructificacion: true },
  { id: 'runtz', nombre: 'Runtz', abrev: 'RZ', grupo: 'hibrida', emoji: '🍬',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Híbrida moderna premium. Engorde gradual de EC en floración.', fructificacion: true },
  { id: 'mac1', nombre: 'MAC #1', abrev: 'MAC', grupo: 'hibrida', emoji: '💎',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2400, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Alien Cookies × Colombian. Muy resinosa; temperatura estable.', fructificacion: true },
  { id: 'wedding_crasher', nombre: 'Wedding Crasher', abrev: 'WCr', grupo: 'hibrida', emoji: '💒',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Wedding Cake × Purple Punch. Aroma dulce; copa aireada.', fructificacion: true },
  { id: 'sunset_sherbet', nombre: 'Sunset Sherbet', abrev: 'Sh', grupo: 'hibrida', emoji: '🌅',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Cookies family. Terpenos intensos; RH controlada en flor.', fructificacion: true },
  { id: 'black_diamond', nombre: 'Black Diamond', abrev: 'BDi', grupo: 'indica', emoji: '💎',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 56, dias: 84,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica morada oscura. Compacta para salas pequeñas.', fructificacion: true },
  { id: 'gelato_auto', nombre: 'Gelato Auto', abrev: 'GLA', grupo: 'auto', emoji: '🍨',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 56, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Auto resinosa. 18/6 constante; no defoliar agresivo en flor.', fructificacion: true },
  { id: 'gorilla_auto', nombre: 'Gorilla Auto', abrev: 'GGA', grupo: 'auto', emoji: '🦍',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 63, dias: 84,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Auto potente. Buena aireación de raíz en cubo DWC.', fructificacion: true },
  { id: 'auto_blueberry', nombre: 'Auto Blueberry', abrev: 'AB', grupo: 'auto', emoji: '🫐',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 49, dias: 70,
    ecMin: 1200, ecMax: 1800, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Auto clásica aromática. Ciclo corto; ideal primeros autos.', fructificacion: true },
  { id: 'auto_purple_lemon', nombre: 'Auto Purple Lemon', abrev: 'APL', grupo: 'auto', emoji: '🍋',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 56, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Auto morada cítrica. Compacta; buena para torres bajas.', fructificacion: true },
  { id: 'acdc', nombre: 'ACDC', abrev: 'AC', grupo: 'cbd', emoji: '🩺',
    tipoFloracion: 'foto', diasVeg: 42, diasFlor: 63, dias: 105,
    ecMin: 1000, ecMax: 1500, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'CBD muy alto. EC moderada; vigilar bloqueo por pH alto.', fructificacion: true },
  { id: 'cannatonic', nombre: 'Cannatonic', abrev: 'CT', grupo: 'cbd', emoji: '💚',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1000, ecMax: 1600, phMin: 5.9, phMax: 6.3, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'CBD dominante equilibrado. Menos estrés osmótico que THC altas.', fructificacion: true },
  { id: 'chocolate_haze', nombre: 'Chocolate Haze', abrev: 'CHz', grupo: 'sativa', emoji: '🍫',
    tipoFloracion: 'foto', diasVeg: 49, diasFlor: 70, dias: 119,
    ecMin: 1400, ecMax: 2200, phMin: 5.9, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Sativa legendaria. Ciclo largo; espacio vertical en flor.', fructificacion: true },
  { id: 'banana_kush', nombre: 'Banana Kush', abrev: 'BKu', grupo: 'indica', emoji: '🍌',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 2000, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Indica aromática dulce. Altura media; buena en RDWC.', fructificacion: true },
  { id: 'cherry_pie', nombre: 'Cherry Pie', abrev: 'CP', grupo: 'hibrida', emoji: '🍒',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Durban × Granddaddy Purple. Cogollos coloridos y densos.', fructificacion: true },
  { id: 'fire_og', nombre: 'Fire OG', abrev: 'FO', grupo: 'hibrida', emoji: '🔥',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1500, ecMax: 2400, phMin: 5.8, phMax: 6.1, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'OG Kush elite. EC alta en flor; raíces oxigenadas 24 h.', fructificacion: true },
  { id: 'northern_lights', nombre: 'Northern Lights', abrev: 'NLf', grupo: 'indica', emoji: '🌌',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Fotoperiódica clásica (no auto). Referencia indica en hidro.', fructificacion: true },
  { id: 'blue_cheese', nombre: 'Blue Cheese', abrev: 'BC', grupo: 'indica', emoji: '🧀',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Blueberry × Cheese. Aroma fuerte; filtro de olor recomendado.', fructificacion: true },
  { id: 'amnesia_auto', nombre: 'Amnesia Haze Auto', abrev: 'AHA', grupo: 'auto', emoji: '☀️',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 70, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.3, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Auto sativa larga. Planifica altura de lámpara desde veg.', fructificacion: true },
  // Marcas Top España
  { id: 'white_truffle', nombre: 'White Truffle', abrev: 'WT', grupo: 'hibrida', emoji: '🍄',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Spain Seeds. Potencia y sabor excepcionales. Engorde gradual de EC en floración.', breederId: 'spain_seeds', fructificacion: true },
  { id: 'zookies', nombre: 'Zookies', abrev: 'ZK', grupo: 'hibrida', emoji: '🍪',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Spain Seeds. Animal Cookies × Gorilla Glue. Resina abundante; pH estable en RDWC.', breederId: 'spain_seeds', fructificacion: true },
  { id: 'zaza', nombre: 'Zaza', abrev: 'ZZ', grupo: 'hibrida', emoji: '💎',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Spain Seeds. Blue Dream × Purple Punch. Terpenos intensos; temperatura estable.', breederId: 'spain_seeds', fructificacion: true },
  { id: 'gelatti', nombre: 'Gelatti', abrev: 'GLT', grupo: 'hibrida', emoji: '🍨',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2300, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Spain Seeds. Gelato × Biscotti. Cogollos densos; buena aireación bajo copa.', breederId: 'spain_seeds', fructificacion: true },
  { id: 'zombie_kush', nombre: 'Zombie Kush', abrev: 'ZKU', grupo: 'indica', emoji: '🧟',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 56, dias: 84,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Ripper Seeds. Amnesia × Lavender. Indica potente; vigilar humedad en floración.', breederId: 'ripper_seeds', fructificacion: true },
  { id: 'magnum', nombre: 'Magnum', abrev: 'MG', grupo: 'auto', emoji: '🔫',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 63, dias: 84,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Buddha Seeds. Auto grande y productiva. Buena luz en floración; altura media.', breederId: 'buddha_seeds', fructificacion: true },
  { id: 'deimos', nombre: 'Deimos', abrev: 'DM', grupo: 'auto', emoji: '🌑',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 56, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Buddha Seeds. Auto vigorosa y productiva. Ideal para torres bajas.', breederId: 'buddha_seeds', fructificacion: true },
  { id: 'critical_soma', nombre: 'Critical Soma', abrev: 'CS', grupo: 'indica', emoji: '🌿',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Advanced Seeds. Critical Mass × Somango. Cogollos pesados; soporte de ramas.', breederId: 'advanced_seeds', fructificacion: true },
  { id: 'chocolate_kush_00', nombre: 'Chocolate Kush', abrev: 'CK', grupo: 'indica', emoji: '🍫',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: '00 Seeds. Chocolate Thai × Kush. Aroma intenso; filtro de carbón recomendado.', breederId: '00_seeds', fructificacion: true },
  { id: 'malawi', nombre: 'Malawi', abrev: 'MW', grupo: 'sativa', emoji: '🇲🇼',
    tipoFloracion: 'foto', diasVeg: 56, diasFlor: 84, dias: 140,
    ecMin: 1400, ecMax: 2300, phMin: 5.9, phMax: 6.3, dificultad: 'difícil', sistemaIdeal: 'dwc,rdwc',
    nota: 'ACE Seeds. Sativa landrace africana. Ciclo muy largo; espacio vertical alto.', breederId: 'ace_seeds', fructificacion: true },
  { id: 'kritikal_bilbo', nombre: 'Kritikal Bilbo', abrev: 'KB', grupo: 'indica', emoji: '🌲',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Genehtik Seeds. Critical Mass × Bilbo. Cogollos densos; buena producción.', breederId: 'genehtik_seeds', fructificacion: true },
  { id: 'txomango', nombre: 'Txomango', abrev: 'TX', grupo: 'hibrida', emoji: '🥭',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1300, ecMax: 2000, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Genehtik Seeds. Somango × Critical. Aroma afrutado; fácil de cultivar.', breederId: 'genehtik_seeds', fructificacion: true },
  { id: 'juanita_lagrimosa', nombre: 'Juanita la Lagrimosa', abrev: 'JL', grupo: 'cbd', emoji: '💧',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 56, dias: 91,
    ecMin: 1000, ecMax: 1600, phMin: 5.9, phMax: 6.3, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Reggae Seeds. CBD dominante. Efecto equilibrado; EC moderada.', breederId: 'reggae_seeds', fructificacion: true },
  { id: 'captain_future', nombre: 'Captain Future', abrev: 'CF', grupo: 'hibrida', emoji: '🚀',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1500, ecMax: 2400, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Anesia Seeds. THC >30%. Muy potente; subir EC gradual en floración.', breederId: 'anesia_seeds', fructificacion: true },
  { id: 'critical_gb', nombre: 'Critical GB', abrev: 'CGB', grupo: 'indica', emoji: '🌿',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'GB Strains. Critical clásica. Fácil de cultivar; buena producción.', breederId: 'gb_strains', fructificacion: true },
  { id: 'tropicozz', nombre: 'Tropic\'Ozz', abrev: 'TO', grupo: 'hibrida', emoji: '🌴',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Perfect Tree Seeds. Tropicana Cookies × Oz. Terpenos tropicales; temperatura estable.', breederId: 'perfect_tree_seeds', fructificacion: true },
  { id: 'mimooz', nombre: 'Mimooz', abrev: 'MM', grupo: 'hibrida', emoji: '🥭',
    tipoFloracion: 'foto', diasVeg: 35, diasFlor: 63, dias: 98,
    ecMin: 1400, ecMax: 2200, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Perfect Tree Seeds. Mimosa × Oz. Aroma intenso; resina abundante.', breederId: 'perfect_tree_seeds', fructificacion: true },
  { id: 'critical_plus_2', nombre: 'Critical+ 2.0', abrev: 'CP2', grupo: 'indica', emoji: '🌿',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Silent Seeds. Critical mejorada. Producción alta; fácil de cultivar.', breederId: 'silent_seeds', fructificacion: true },
  { id: 'super_critical', nombre: 'Super Critical', abrev: 'SC', grupo: 'indica', emoji: '🌿',
    tipoFloracion: 'foto', diasVeg: 28, diasFlor: 49, dias: 77,
    ecMin: 1200, ecMax: 1900, phMin: 5.8, phMax: 6.1, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Green House Seeds. Critical × Big Bud. Cogollos muy pesados; soporte obligatorio.', breederId: 'green_house_seeds', fructificacion: true },
  { id: 'blue_dream_matic_auto', nombre: 'Blue Dream Matic Auto', abrev: 'BDMA', grupo: 'auto', emoji: '🫐',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 63, dias: 84,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'fácil', sistemaIdeal: 'dwc,rdwc',
    nota: 'Fast Buds. Blue Dream auto. Sativa-dominante; buena luz en floración.', breederId: 'fast_buds', fructificacion: true },
  { id: 'six_shooter_auto', nombre: 'Six Shooter Auto', abrev: 'SSA', grupo: 'auto', emoji: '🔫',
    tipoFloracion: 'auto', diasVeg: 21, diasFlor: 70, dias: 91,
    ecMin: 1300, ecMax: 2100, phMin: 5.8, phMax: 6.2, dificultad: 'media', sistemaIdeal: 'dwc,rdwc',
    nota: 'Fast Buds. Auto muy productiva. Ciclo largo; altura media.', breederId: 'fast_buds', fructificacion: true },
];
